int initializeDatabase();
void closeDatabaseConnection();
const unsigned char *searchClientByCPF(char *cpf);
const unsigned char *searchVehicleByLicensePlate(char* licensePlate);
int registerClient(char* cpf, char* name);
int registerVehicle(char* cpf, char* licensePlate);
int updateClientName(char* cpf, char* name);
int deleteClientAndVehicles(char* cpf);
const char *getClients();
const char *getAllVehiclesByCPF(char *cpf);
float totalLitersFueledByCPF(char *cpf);
int fuelVehicle(char* licensePlate, float liters);
int clearClientPoints(char* cpf);