void showMenu();
void handleSelectChoices();
void handleExitOrGoBackToMainMenu();
void handleRegisterNewVehicle();
void handleRegisterNewClient();
void handleDeleteClient();
void handleChangeClientName();
void handleListAllClients();
void handleListClientVehicles();