int isClientAlreadyRegistered(char* cpf);
int handleRegisterClientInDatabase(char* cpf, char* name);
int handleRegisterVehicleInDatabase(char* cpf, char* licensePlate);
int isVehicleAlreadyRegistered(char* licensePlate);
int handleFuelVehicleInDatabase(char* licensePlate, float liters);
int handleDeleteClientInDatabase(char *cpf);
int handleUpdateClientNameInDatabase(char *cpf, char *name);
int handleClearClientPointsInDatabase(char *cpf);
const char *getAllVehiclesByCPFInDatabase(char *cpf);
const char *getAllClientsInDatabase();
float getTotalLitersFueledByCPFInDatabase(char *cpf);